version: 2.1

workflows:
  test-deploy:
    jobs:
      - frontend
jobs:
  frontend:
    working_directory: ~/kj/frontend
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
        path: ~/kj
      - run:
          name: See directory
          command: ls
      - run:
          name: Go to frontend
          command: cd frontend
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
